### ISSUE TITLE
下拉加载数据最多只能加载1024KB

### ISSUE THREAD

**Issue by 634323580** [coolfishstudio/wechat-webapp-cnode#1]
一直加载一直加载就摆错了，请问有没有解决方法?

**Comment by superwoods** [comment]
估计要等正式发布版了，因为内测目的就是让大家看看基本的代码、API 并非为了制作产品，不过据小道消息（我家CTO&COO说）tt现在是300w一个企业级测试账号，据说是各种功能完备的发布版权限。。。
